services:
  db:
    image: postgres:alpine
    container_name: fabricaPastas
    restart: always
    environment:
      POSTGRES_PASSWORD: fabricaPastas
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "6666:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: