# Generated by Django 5.2.3 on 2025-06-25 03:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='EstadoReserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='HorarioTurno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horaInicio', models.TimeField()),
                ('horaFin', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(unique=True)),
                ('capacidad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Plato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField()),
                ('precioUnitario', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='RolEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField()),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField()),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TipoPlato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField()),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Cobro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('total', models.FloatField()),
                ('idMetodoPago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fabricaPastas.metodopago')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaHoraEntrega', models.DateTimeField()),
                ('fechaHoraPedido', models.DateTimeField()),
                ('idEmpleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fabricaPastas.empleado')),
                ('idMesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fabricaPastas.mesa')),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('total', models.FloatField()),
                ('idCliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fabricaPastas.cliente')),
                ('idCobro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fabricaPastas.cobro')),
                ('idPedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fabricaPastas.pedido', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('subTotal', models.FloatField()),
                ('idPedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fabricaPastas.pedido')),
                ('idPlato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fabricaPastas.plato')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('subTotal', models.FloatField()),
                ('idFactura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fabricaPastas.factura')),
                ('idPlato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fabricaPastas.plato')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaRealizacionReserva', models.DateField()),
                ('idCliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fabricaPastas.cliente')),
                ('idEstadoReserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fabricaPastas.estadoreserva')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleReserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idMesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fabricaPastas.mesa', unique=True)),
                ('idReserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fabricaPastas.reserva', unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='empleado',
            name='idRol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fabricaPastas.rolempleado'),
        ),
        migrations.AddField(
            model_name='mesa',
            name='idSector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fabricaPastas.sector', unique=True),
        ),
        migrations.CreateModel(
            name='ExS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idEmpleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fabricaPastas.empleado')),
                ('idSector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fabricaPastas.sector')),
            ],
        ),
        migrations.AddField(
            model_name='plato',
            name='idTipoPlato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fabricaPastas.tipoplato'),
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idHorarioTurno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fabricaPastas.horarioturno')),
                ('idServicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fabricaPastas.servicio')),
            ],
        ),
        migrations.AddField(
            model_name='reserva',
            name='idTurno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fabricaPastas.turno'),
        ),
    ]
