# Generated by Django 5.2.3 on 2025-06-27 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabricaPastas', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExS',
            new_name='EmpleadoxSector',
        ),
        migrations.AddField(
            model_name='empleado',
            name='nombre',
            field=models.CharField(default=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='apellido',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='detallereserva',
            name='idMesa',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='fabricaPastas.mesa'),
        ),
        migrations.AlterField(
            model_name='detallereserva',
            name='idReserva',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='fabricaPastas.reserva'),
        ),
        migrations.AlterField(
            model_name='estadoreserva',
            name='nombre',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='factura',
            name='idPedido',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='fabricaPastas.pedido'),
        ),
        migrations.AlterField(
            model_name='mesa',
            name='idSector',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='fabricaPastas.sector'),
        ),
        migrations.AlterField(
            model_name='metodopago',
            name='nombre',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='plato',
            name='nombre',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='rolempleado',
            name='nombre',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='sector',
            name='nombre',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='nombre',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='tipoplato',
            name='nombre',
            field=models.CharField(max_length=20),
        ),
    ]
