# Generated by Django 3.2.24 on 2025-06-28 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Cobro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('total', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoReserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='HorarioTurno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horaInicio', models.TimeField()),
                ('horaFin', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(unique=True)),
                ('capacidad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='RolEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TipoPlato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idHorarioTurno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.horarioturno')),
                ('idServicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.servicio')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaRealizacionReserva', models.DateField()),
                ('idCliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.cliente')),
                ('idEstadoReserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.estadoreserva')),
                ('idTurno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.turno')),
            ],
        ),
        migrations.CreateModel(
            name='Plato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, unique=True)),
                ('descripcion', models.TextField()),
                ('precioUnitario', models.FloatField()),
                ('idTipoPlato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.tipoplato')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaHoraEntrega', models.DateTimeField()),
                ('fechaHoraPedido', models.DateTimeField()),
                ('idEmpleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.empleado')),
                ('idMesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.mesa')),
            ],
        ),
        migrations.AddField(
            model_name='mesa',
            name='idSector',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='portal.sector'),
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('total', models.FloatField()),
                ('idCliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.cliente')),
                ('idCobro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.cobro')),
                ('idPedido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='portal.pedido')),
            ],
        ),
        migrations.CreateModel(
            name='EmpleadoxSector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idEmpleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.empleado')),
                ('idSector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.sector')),
            ],
        ),
        migrations.AddField(
            model_name='empleado',
            name='idRol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.rolempleado'),
        ),
        migrations.CreateModel(
            name='DetalleReserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idMesa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='portal.mesa')),
                ('idReserva', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='portal.reserva')),
            ],
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('subTotal', models.FloatField()),
                ('idPedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.pedido')),
                ('idPlato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.plato')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('subTotal', models.FloatField()),
                ('idFactura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.factura')),
                ('idPlato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.plato')),
            ],
        ),
        migrations.AddField(
            model_name='cobro',
            name='idMetodoPago',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.metodopago'),
        ),
    ]
